---
# 여러 번 실행해도 안전하도록 설계
# - 미정의 변수는 빈 리스트로 처리
# - 존재하지 않는 서비스/패키지/규칙이어도 실패로 보지 않음
# - firewalld가 실행 중일 때만 immediate 적용

- name: 패키지/서비스 팩트 수집
  ansible.builtin.package_facts:
    manager: auto

- name: 서비스 팩트 수집
  ansible.builtin.service_facts:

- name: firewalld 설치/실행 여부 계산
  ansible.builtin.set_fact:
    firewalld_installed: "{{ 'firewalld' in (ansible_facts.packages | default({})) }}"
    firewalld_running: >-
      {{ (ansible_facts.services['firewalld.service'] | default({})).state == 'running' }}
  tags: [firewalld]

# --------- 방화벽 규칙 해제(서비스) ----------
- name: firewalld 서비스 규칙 제거
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: "{{ fw_zone | default('public') }}"
    permanent: true
    immediate: "{{ firewalld_running }}"
    state: disabled
  loop: "{{ fw_svcs | default([]) }}"
  when: firewalld_installed and (fw_svcs | default([]) | length) > 0
  register: rm_fw_services
  failed_when: false
  tags: [firewalld]

# --------- 방화벽 규칙 해제(포트) ----------
- name: firewalld 포트 규칙 제거
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: "{{ fw_zone | default('public') }}"
    permanent: true
    immediate: "{{ firewalld_running }}"
    state: disabled
  loop: "{{ fw_ports | default([]) }}"
  when: firewalld_installed and (fw_ports | default([]) | length) > 0
  register: rm_fw_ports
  failed_when: false
  tags: [firewalld]

# --------- 서비스 중지/비활성 ----------
- name: 서비스 중지 및 부팅 비활성화
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ svcs | default([]) }}"
  when: (svcs | default([]) | length) > 0
  failed_when: false
  tags: [service]

# --------- 설정 파일/디렉터리 제거 ----------
- name: 설정 파일/디렉터리 제거
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files | default([]) }}"
  when: (files | default([]) | length) > 0
  tags: [files]

# --------- 패키지 제거 ----------
- name: 패키지 제거 (플랫폼 중립)
  ansible.builtin.package:
    name: "{{ pkgs | default([]) }}"
    state: absent
  when: (pkgs | default([]) | length) > 0
  failed_when: false
  tags: [package]
